
name: Test GitHub Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make dummy change
        run: |
          echo "Last updated: $(date -u)" > dummy.txt

      - name: Commit and push changes
        run: |
          git config user.name "zuki-auto-updater"
          git config user.email "zuki@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.ZUKI_TOKEN }}@github.com/winter-fortress/zuki-elementals.git
          git add dummy.txt
          git commit -m "🧪 Test push with dummy.txt" || echo "No changes to commit"
          git push
