name: Update owners.json

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-owners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run update-owners script
        run: node .github/scripts/update-owners.js

      - name: Commit and push changes
        run: |
          git config user.name "zuki-auto-updater"
          git config user.email "zuki@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.ZUKI_TOKEN }}@github.com/winter-fortress/zuki-elementals.git
          git add public/owners.json
          git commit -m "🔄 Auto-update owners.json" || echo "No changes to commit"
          git push
